inclusiveedudjango/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('themes.urls')),
    path('admin/', admin.site.urls),
]

themes/urls.py
from django.urls import path

from . import views


app_name = 'themes'
urlpatterns = [
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    
    path('', views.index, name='index'),
    path('<int:pk>/', views.theme, name='theme'),
]

themes/models.py
from statistics import mode
from django.db import models


class Theme(models.Model):
    name = models.CharField(max_length=1000)
    theory = models.CharField(max_length=1000)
    video = models.CharField(max_length=1000)
    matches = models.CharField(max_length=1000)
    missing_word = models.CharField(max_length=1000)
    right_order = models.CharField(max_length=1000)
    right_answer = models.CharField(max_length=1000)

    class Meta:
        verbose_name = 'Тема'
        verbose_name_plural = 'Темы'

    def __str__(self) -> str:
        return self.name

themes/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from .models import Theme


def loginPage(request):
    if request.user.is_authenticated:
        return redirect('/') 
    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect('/')
            else:
                messages.info(request, 'Логин или пароль введен неверно')

        return render(request, 'themes/login.html', {})


def logoutUser(request):
    logout(request)
    return redirect('/login')


@login_required(login_url='/login')
def index(request):
    theme_objects = Theme.objects.all()
    return render(request, 'themes/index.html', {'theme_objects': theme_objects})


@login_required(login_url='/login')
def theme(request, pk):
    theme_object = Theme.objects.get(pk=pk)
    theme_objects = Theme.objects.all()
    return render(request, 'themes/theme.html', {
            'theme_object': theme_object,
            'theme_objects': theme_objects,
        })

themes/templates/themes/index.html
{% extends "themes/wrapper.html" %}

{% block content %}
<div class="container__content__main row">
  <div class="container__content__main__left col-md-3">
    <div class="container__content__main__left__theme">
      Тема
    </div>
    <div class="container__content__main__left__lessons">
      <ul class="container__content__main__left__lessons__ul">
        {% for theme in theme_objects %}
          <li class="container__content__main__left__lessons__ul__li">
            <a 
              class="container__content__main__left__lessons__ul__li_ref"
              href="{% url 'themes:theme' theme.pk %}"
            >
                {{ theme.name }}
            </a> 
          </li>
        {% endfor %}
      </ul>
    </div>
  </div>
</div>
{% endblock %}

themes/templates/themes/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'themes/css/login/style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" 
        integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <title>Login</title>
</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">Авторизация</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
            {% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="Пользователь..." class="form-control">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								<input type="password" name="password" placeholder="Пароль..." class="form-control" >
						</div>
							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Войти">
				   			</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</body>
</html>

themes/templates/themes/theme.html
{% extends "themes/wrapper.html" %}
{%load static%}
{% block content %}
<div class="container__content__theme row mt-2">
    <h4 class="container__content__theme__name">{{ theme_object.name }}</h4>
</div>
<div class="container__content__main row">
    <div class="container__content__main__left col-md-3">
        <div class="container__content__main__left__theme">
            Тема
        </div>
        <div class="container__content__main__left__lessons">
            <ul class="container__content__main__left__lessons__ul">
                {% for theme in theme_objects %}
                    <li class="container__content__main__left__lessons__ul__li">
                        <a class="container__content__main__left__lessons__ul__li_ref" href="{% url 'themes:theme' theme.pk %}">{{ theme.name }}</a> 
                    </li>
                    <hr>
                {% endfor %}
            </ul>
        </div>
    </div>
    <div class="container__content__main__center col-md-2">
        <div class="container__content__main__center__buttons">
            <button id="theory" class="container__content__main__center__buttons__button text-center">
                <img class="container__content__main__center__buttons__button__img"
                    src="{% static 'themes/icons/1.png' %}" alt="photo">
                <p class="container__content__main__center__buttons__button__p">Теория</p>
            </button>
            <button id="video" class="container__content__main__center__buttons__button text-center">
                <img class="container__content__main__center__buttons__button__img"
                    src="{% static 'themes/icons/2.png' %}" alt="photo">
                <p class="container__content__main__center__buttons__button__p">Видеообъяснение</p>
            </button>
            <button id="matches" class="container__content__main__center__buttons__button text-center">
                <img class="container__content__main__center__buttons__button__img"
                    src="{% static 'themes/icons/3.png' %}" alt="photo">
                <p class="container__content__main__center__buttons__button__p">Установите соответствия</p>
            </button>
            <button id="missing_word" class="container__content__main__center__buttons__button text-center">
                <img class="container__content__main__center__buttons__button__img"
                    src="{% static 'themes/icons/4.png' %}" alt="photo">
                <p class="container__content__main__center__buttons__button__p">Вставьте пропущенное слово</p>
            </button>
            <button id="right_order" class="container__content__main__center__buttons__button text-center">
                <img class="container__content__main__center__buttons__button__img"
                    src="{% static 'themes/icons/5.png' %}" alt="photo">
                <p class="container__content__main__center__buttons__button__p">Расположите в правильном порядке</p>
            </button>
            <button id="right_answer" class="container__content__main__center__buttons__button text-center">
                <img class="container__content__main__center__buttons__button__img"
                    src="{% static 'themes/icons/6.png' %}" alt="photo">
                <p class="container__content__main__center__buttons__button__p">Выберите правильный ответ</p>
            </button>
        </div>
    </div>
    <div class="container__content__main__right col-md-7">
        <div class="container__content__main__right__option">
            <span id="title" class="container__content__main__right__option__name">

            </span>
        </div>
        <div id="content" class="container__content__main__right__interactive">

        </div>
    </div>
</div>
<script type="text/javascript">
    var theory = document.getElementById('theory');
    var video = document.getElementById('video');
    var matches = document.getElementById('matches');
    var missing_word = document.getElementById('missing_word');
    var right_order = document.getElementById('right_order');
    var right_answer = document.getElementById('right_answer');

    var title = document.getElementById('title');
    var content = document.getElementById('content');

    theory.addEventListener('click', event => {
        title.textContent = theory.textContent;
        content.innerHTML = '{{ theme_object.theory|safe }}';
    });
    video.addEventListener('click', event => {
        title.textContent = video.textContent;
        content.innerHTML = '{{ theme_object.video|safe }}';
    });
    matches.addEventListener('click', event => {
        title.textContent = matches.textContent;
        content.innerHTML = '{{ theme_object.matches|safe }}';
    });
    missing_word.addEventListener('click', event => {
        title.textContent = missing_word.textContent;
        content.innerHTML = '{{ theme_object.missing_word|safe }}';
    });
    right_order.addEventListener('click', event => {
        title.textContent = right_order.textContent;
        content.innerHTML = '{{ theme_object.right_order|safe }}';
    });
    right_answer.addEventListener('click', event => {
        title.textContent = right_answer.textContent;
        content.innerHTML = '{{ theme_object.right_answer|safe }}';
    });
    
</script>
{% endblock %}

themes/templates/themes/wrapper.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'themes/css/main/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>Inclusive Edu</title>
</head>
<body>
    <div class="main-wrapper" style="background-color: #D6D0F0;">
        <div class="top">
            <a href="/" class="top__title">
                <h2 class="top__title__h2">Inclusive Edu</h2>
            </a>
            <div class="top__content">
                <div class="top__content__nav">
                    <a href="/" class="top__content__nav__reference">
                        Главная
                    </a>
                    <a href="/" class="top__content__nav__reference">
                        О нас
                    </a>
                    <a href="/" class="top__content__nav__reference">
                        Глоссарий
                    </a>
                </div>
            </div>
            <div class="top__block">
                <a class="top__block__logout" href="{% url 'themes:logout' %}">Выйти</a>
            </div>
        </div>
        <div class="mt-3 container-fluid h-100">
            <div class="container__content__subject row">
                <h3 class="container__content__subject__name">Информатика 7</h3>
            </div>
            {% block content %}
            {% endblock %}
        </div>
    </div>
</body>
</html>